"""empty message

Revision ID: 232f9941867e
Revises: 8fdb479d08e5
Create Date: 2021-12-17 00:21:40.018913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '232f9941867e'
down_revision = '8fdb479d08e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('title', sa.Column('series_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_title_series_id'), 'title', ['series_id'], unique=False)
    op.create_foreign_key(None, 'title', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'title', type_='foreignkey')
    op.drop_index(op.f('ix_title_series_id'), table_name='title')
    op.drop_column('title', 'series_id')
    # ### end Alembic commands ###
