"""empty message

Revision ID: ea563b79c0b5
Revises: 82182c9eb1e0
Create Date: 2021-12-07 23:29:16.331209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea563b79c0b5'
down_revision = '82182c9eb1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('owner', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'owner')
    # ### end Alembic commands ###
