"""empty message

Revision ID: 254f1d262e77
Revises: 3a626afd4260
Create Date: 2021-09-19 17:25:08.058510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254f1d262e77'
down_revision = '3a626afd4260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
