"""empty message

Revision ID: 3a626afd4260
Revises: 
Create Date: 2021-09-17 18:40:31.415316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a626afd4260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('district', sa.Enum('district_1', 'district_2', 'district_3', 'district_4', 'district_5', 'district_6', 'district_7', name='districtenum'), nullable=False),
    sa.Column('ward', sa.Enum('ward_a', 'ward_b', 'ward_c', 'ward_d', 'ward_e', 'ward_f', 'ward_g', name='wardenum'), nullable=False),
    sa.Column('vip', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citizen_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
